# Generated by Django 4.1.5 on 2023-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_paiment_student_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photoEtudiant',
            field=models.ImageField(blank=True, default='./default.png', null=True, upload_to='img_student'),
        ),
    ]
